apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-content-monitor-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/file_content_monitor"